services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    command:
      - odoo
      - "--init"
      - base,account,fr_gold_taxes
      - "-d"
      - mydb
      - "--without-demo=all"
      - "--load-language=fr_FR"
      - "--dev=all"
    ports:
      - "8069:8069"
    volumes:
      - ./fr_gold_taxes:/mnt/extra-addons/fr_gold_taxes
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

volumes:
  odoo-db-data:
  odoo-web-data:
