from . import livre_police_referentiel
from . import livre_police_provenance
from . import livre_police_qualite
from . import res_partner
from . import product_template
from . import sale_order
from . import account_move
from . import stock_picking
from . import stock_lot
from . import stock_poids
from . import livre_police_page
from . import livre_police_transfert
from . import livre_police_reprise
from . import livre_police_ligne
from . import livre_police_rectification
from . import livre_police_rectification_quantite
from . import livre_police_controle
from . import livre_police_consultation
